import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './(Header)/Header'; // Import Header component
import AuthProvider from './context/AuthProvider';
import Context from './context/Context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>{/* Add your head content here if needed */}</head>
      <body>
        <AuthProvider>
          <Context>
            <Header />
            {children}
          </Context>
        </AuthProvider>
      </body>
    </html>
  );
}
