// RootLayout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './(Header)/Header'; // Import Header component
import AuthProvider from './context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Add your head content here if needed */}
      </head>
      <body className="flex text-center items-center flex-col min-h-screen">
        <header> {/* Place Header component here */}
          <Header />
        </header>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
